version: '3'

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    
    container_name: ${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data